[package]
name = "craft_buddy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mki_fork = "0.2.1"
clipboard = "0.5.0"